# Site settings
title: JMIG5776
name: Jogi Miglani
tagline: 'Fitness Freak'
subtitle: Breaking to blogging life
email: jmig5776@gmail.com
description: >
  Fitness Freak and IITian from Punjab sorting up his messed up life.
baseurl: ""
url: "https://jmig5776.github.io/"
github_username:  jmig5776
disqus_baseurl: "https://jmig5776.github.io/"
disqus_shortname: https-jmig5776-github-io
permalink: :title

excerpt_seperator: <!-break->


# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
version: 1.0.1

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jogi Miglani"


# About/contact
author:
  name:             Jogi Miglani
  github:           jmig5776
  email:            jmig5776@gmail.com
  linkedin:         Jogi Miglani
  gravatar_md5:  698c02e024b7ac507f34a21148eedb9a

# External plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
